# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-21 07:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Currency')),
            ],
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('fax_no', models.CharField(blank=True, max_length=20, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('default_currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Currency')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsurerRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_agency', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
                ('effective_date', models.DateField()),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='products.Insurer')),
            ],
        ),
        migrations.CreateModel(
            name='InsurerTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('insurer_name', models.CharField(max_length=100)),
                ('insurer_official_name', models.CharField(max_length=100)),
                ('official_website', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('office_address', models.TextField(blank=True, null=True)),
                ('offerings', models.TextField(blank=True, null=True)),
                ('special_features', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='products.Insurer')),
            ],
            options={
                'default_related_name': 'translations',
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='insurertranslation',
            unique_together=set([('insurer', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='insurerrating',
            unique_together=set([('insurer', 'rating_agency', 'effective_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set([('currency', 'effective_date')]),
        ),
    ]
