# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipatingDetailValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProdID', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Gender', models.BooleanField()),
                ('Smoker', models.BooleanField()),
                ('PolicyYear', models.IntegerField()),
                ('SumAssuredFrom', models.IntegerField()),
                ('SumAssuredTo', models.IntegerField()),
                ('GuarCashValue_intercept', models.IntegerField()),
                ('GuarCashValue_slope', models.FloatField()),
                ('GuarDeathBenefit_intercept', models.IntegerField()),
                ('GuarDeathBenefit_slope', models.FloatField()),
                ('NonGuarCashValue_intercept', models.IntegerField()),
                ('NonGuarCashValue_slope', models.FloatField()),
                ('NonGuarTCashValue_intercept', models.IntegerField()),
                ('NonGuarTCashValue_slope', models.FloatField()),
                ('NonGuarDeathBenefit_intercept', models.IntegerField()),
                ('NonGuarDeathBenefit_slope', models.FloatField()),
                ('NonGuarTDeathBenefit_intercept', models.IntegerField()),
                ('NonGuarTDeathBenefit_slope', models.FloatField()),
                ('LastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='participatingdetailvalues',
            index_together=set([('Age', 'Gender', 'Smoker', 'ProdID')]),
        ),
    ]
