# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='fax_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
